### ISSUE TITLE
Allow http in build arg / environment

### ISSUE THREAD

**Issue by tperrindell** [n-stone/docker-bastillion#3]
Hi !

I was working to build a version of bastillion on OpenJDK > 9 and I found your page :)

2 questions : 
- Can you make the http / https scheme a choice ? I am using traefik to route trafic, and I don't need bastillion to run as https (I know how to do it, but I think it's a good feature to offer)
- Have you tried to setup a AD server for auth using JDK 11 ?
Thanks,

**Comment by mietzen** [comment]
> Can you make the http / https scheme a choice ? I am using traefik to route trafic, and I don't need bastillion to run as https (I know how to do it, but I think it's a good feature to offer)

I'll activate http and https by default in a new release. For now you can simply create a `start.ini` file with the following content:

```
--module=client
--module=ext
--module=server
--module=jsp
--module=resources
--module=deploy
--module=jstl
--module=websocket
--module=http
```

Then run:

`docker run -d -p 8080:8080  -v $(pwd)/keydb:/keydb -v $(pwd)/start.ini:/opt/bastillion/jetty/start.ini mietzen/bastillion:3.14.0`

> Have you tried to setup a AD server for auth using JDK 11 ?

No, never tried it.
