### ISSUE TITLE
3.14.0 Error 503. 

### ISSUE THREAD

**Issue by gonzalu** [n-stone/docker-bastillion#6]
I am getting an error on the latest... 3.13.00 not having same error

![image](https://github.com/mietzen/docker-bastillion/assets/32348862/04453fa8-fa7e-4dbe-b85b-2ec55a81d578)

**Comment by gonzalu** [comment]
If I remove the following lines from the docker-compose.yaml, it now starts OK.

      - DB_USER=bastillion # Database user
      - DB_PASSWORD='' #Database password
      - DB_CONNECTION_URL='jdbc:h2:keydb/bastillion;CIPHER=AES' #Connection URL to the DB

**Comment by mietzen** [comment]
bastillion itself is no longer maintained: https://github.com/bastillion-io/Bastillion/issues/506#issuecomment-1627688349

I updated the `readme.md ` and I'm going to archive this Repo. 

**Alternatives:**

- https://github.com/warp-tech/warpgate
- https://github.com/ovh/the-bastion
